---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# pkgdep

The goal of pkgdep is to provide a nice API for analyzing the dependency structure from the return value of `available.packages()` and other functions.

## Example

```{r eval = FALSE}
library(pkgdep)
```


```{r echo=FALSE}
devtools::load_all(quiet = TRUE)
```

```{r}
library(tibble)
library(dplyr)
library(tidyr)
```

```{r}
pkgdep <- as_pkgdep(available.packages())

tibble_revdeps <- get_revdeps("tibble", pkgdep)
tibble_revdeps

# All dependencies of tibble
all_tibble_deps <- get_all_deps("tibble", pkgdep, c("Depends", "Imports"))
as_tibble(all_tibble_deps)

# Some packages are listed more than once:
as_tibble(all_tibble_deps) %>% 
  count(Dep) %>% 
  arrange(-n)

# All packages used for revdep-checking tibble
all_tibble_revdep_deps <- get_all_deps(tibble_revdeps, pkgdep)
as_tibble(all_tibble_revdep_deps)

# Separate dependency graphs for each revdep of tibble
individual_tibble_revdep_deps <-
  tibble(revdep = tibble_revdeps) %>%
  rowwise() %>% 
  mutate(all_deps = list(get_all_deps(revdep, pkgdep))) %>%
  ungroup()

# How many times is each package used during the revdepcheck process,
# excluding direct dependencies of tibble?
individual_tibble_revdep_deps %>%
  rowwise() %>%
  mutate(all_pkgs = list(unique(all_deps$Dep))) %>%
  select(-all_deps) %>%
  unnest() %>%
  count(all_pkgs) %>%
  filter(!(all_pkgs %in% all_tibble_deps$Dep)) %>%
  arrange(-n) %>%
  print(n = 20)
```

